In [708]:
import pandas as pd
import sklearn
from sklearn import svm, preprocessing
from numpy import *
from sklearn import metrics
from sklearn.preprocessing import StandardScaler
from sklearn.linear_model import SGDRegressor
from sklearn.neighbors import KNeighborsRegressor
from sklearn.model_selection import RandomizedSearchCV
from sklearn.model_selection import GridSearchCV
import numpy as np
import openpyxl
from array import *
from numpy import *

In [709]:
'''Reading of training data'''
data = pd.read_excel (r'E:/flipr hackathon/problem_statement/Data.xlsx',sheet_name='Train_Data')

In [710]:
'''Setting player as index'''
data = data.set_index('PLAYER')

In [711]:
data.head()

,Mat,Inns,NO,2018_Runs,HS,Avg,BF,SR,100,50,4s,6s,2019_Runs
PLAYER,,,,,,,,,,,,,
Aaron Finch,10,9,1,134,46,16.75,100,134.00,0,0,6,8,160
AB de Villiers,12,11,2,480,90,53.33,275,174.54,0,6,39,30,424
Abhishek Sharma,3,3,2,63,46,63.00,33,190.90,0,0,3,5,63
Ajinkya Rahane,15,14,1,370,65,28.46,313,118.21,0,1,39,5,396
Alex Hales,6,6,0,148,45,24.66,118,125.42,0,0,13,6,165

In [712]:
'''Removing * from HS column and replacing - with 0 in Avg'''
hs = list(data['HS'])
vivek = []
for i in hs:
    if type(i)==str:
        z=i.replace('*','')
        vivek.append(z)
    else:
        vivek.append(i)
viv = [int(i) for i in vivek]
data['HS'] = viv

avg = list(data['Avg'])
for index,item in enumerate(avg):
    if item== '-':
        avg[index] = 0
data_test['Avg'] = avg

In [713]:
'''Shuffling of data'''
data = sklearn.utils.shuffle(data)
data.shape

(100, 13)

In [714]:
X = data.drop("2019_Runs", axis=1).values
X = preprocessing.scale(X)
y = data['2019_Runs'].values

In [715]:
'''First traning only 70% '''
X_train = X[:-30]
X_test = X[-30:]

y_train = y[:-30]
y_test = y[-30:]

In [716]:
'''loss = ['squared_loss', 'huber', 'epsilon_insensitive', 'squared_epsilon_insensitive']
penalty = ['l1', 'l2', 'elasticnet'] 
alpha = [0.0001, 0.001, 0.01, 0.1, 1, 10, 100, 1000] 
learning_rate = ['constant', 'optimal', 'invscaling', 'adaptive'] 
#class_weight = [{1:0.5, 0:0.5}, {1:0.4, 0:0.6}, {1:0.6, 0:0.4}, {1:0.7, 0:0.3}] 
eta0 = [1, 10, 100] 
param_distributions = dict(loss=loss, 
penalty=penalty, 
alpha=alpha, 
learning_rate=learning_rate, 
eta0=eta0) 
sgd = SGDRegressor(loss="squared_loss", penalty="l2", max_iter=10000) 
random = GridSearchCV(estimator=sgd, 
param_grid=param_distributions, 
scoring='v_measure_score', 
verbose=1, n_jobs=-1) 
random_result = random.fit(X_train, y_train) 
print('Best Score: ', random_result.best_score_) 
print('Best Params: ', random_result.best_params_)
'''
clf = SGDRegressor(max_iter=10000)
clf.fit(X_train, y_train)
y_pred = clf.predict(X_test)
print(metrics.mean_absolute_error(y_test, y_pred))
print((clf.score(X_test, y_test))*100)
for x,y in list(zip(y_pred,y_test)):
    print(x,y)

17.866582186248458
98.3566229058172
390.6052275698129 373
0.1304091005509349 12
496.92873200509723 442
46.74883217040727 19
144.61666036395428 156
208.00919577349083 211
598.4632628273577 593
256.56112872463495 282
56.46763164740031 70
129.73322829740619 101
91.23092984064816 81
55.792959529044566 42
-5.2411710334256725 12
288.67706610772984 332
494.92649916019684 464
244.70691443125924 282
42.43342869363693 40
124.08383749633217 98
71.81982528063125 63
445.870677277603 463
95.94231857315387 90
0.8962296631290485 11
-2.5030837558580856 12
128.38584999220427 98
388.005366156066 383
156.40497303181297 162
503.3634760799986 510
64.4205946323976 64
141.96236701554255 115
206.47431375979863 183

In [717]:
#training the whole data
data = pd.read_excel (r'E:/flipr hackathon/problem_statement/Data.xlsx',sheet_name='Train_Data')
data = data.set_index('PLAYER')

hs = list(data['HS'])
vivek = []
for i in hs:
    if type(i)==str:
        z=i.replace('*','')
        vivek.append(z)
    else:
        vivek.append(i)
viv = [int(i) for i in vivek]
data['HS'] = viv

avg = list(data_test['Avg'])
for index,item in enumerate(avg):
    if item== '-':
        avg[index] = 0
data_test['Avg'] = avg

data = sklearn.utils.shuffle(data)

X = data.drop("2019_Runs", axis=1).values
X_tr = preprocessing.scale(X)
print(X_tr.shape)
y_tr = data['2019_Runs'].values

clf = SGDRegressor(max_iter=10000)
clf.fit(X_tr, y_tr)


data_test = pd.read_excel (r'E:/flipr hackathon/problem_statement/Data.xlsx',sheet_name='Test_Data')
player = list(data_test['PLAYER'])
data_test = data_test.set_index('PLAYER')


hs_test = list(data_test['HS'])
viv = []
for i in hs_test:
    if type(i)==str:
        z=i.replace('*','')
        viv.append(z)
    else:
        viv.append(i)

viv = [int(i) for i in viv]
data_test['HS'] = viv
data_test.head()

(100, 12)

,Mat,Inns,NO,2019_Runs,HS,Avg,BF,SR,100,50,4s,6s
PLAYER,,,,,,,,,,,,
David Warner,12,12,2,692,100,69.2,481,143.86,1,8,57,21
KL Rahul,14,14,3,593,100,53.9,438,135.38,1,6,49,25
Quinton de Kock,16,16,1,529,81,35.26,398,132.91,0,4,45,25
Shikhar Dhawan,16,16,1,521,97,34.73,384,135.67,0,5,64,11
Andre Russell,14,13,4,510,80,56.66,249,204.81,0,4,31,52

In [718]:
avg = list(data_test['Avg'])
for index,item in enumerate(avg):
    if item== '-':
        avg[index] = 0
data_test['Avg'] = avg
data_test.head()

,Mat,Inns,NO,2019_Runs,HS,Avg,BF,SR,100,50,4s,6s
PLAYER,,,,,,,,,,,,
David Warner,12,12,2,692,100,69.20,481,143.86,1,8,57,21
KL Rahul,14,14,3,593,100,53.90,438,135.38,1,6,49,25
Quinton de Kock,16,16,1,529,81,35.26,398,132.91,0,4,45,25
Shikhar Dhawan,16,16,1,521,97,34.73,384,135.67,0,5,64,11
Andre Russell,14,13,4,510,80,56.66,249,204.81,0,4,31,52

In [719]:
X_tes = data_test.values
X_tes = preprocessing.scale(X_tes)
print(X_tes.shape)
y_pred = clf.predict(X_tes)

y_pred = [abs(int(a)) for a in y_pred]
print((y_pred))
print(player)
play = []
for i in player:
    if type(i)==str:
        z=i.replace('\xa0',' ')
        play.append(z)
        
print(play)

(100, 12)
[581, 541, 519, 514, 486, 489, 462, 431, 461, 405, 422, 416, 404, 419, 418, 390, 452, 399, 377, 414, 383, 394, 330, 347, 319, 330, 308, 312, 305, 328, 296, 299, 284, 258, 237, 221, 214, 212, 223, 177, 166, 170, 208, 156, 174, 166, 143, 134, 118, 134, 120, 107, 101, 97, 116, 107, 83, 85, 75, 96, 85, 74, 70, 69, 73, 56, 70, 63, 44, 48, 42, 51, 36, 49, 30, 52, 44, 26, 23, 33, 11, 10, 1, 25, 5, 11, 2, 13, 3, 7, 7, 8, 4, 4, 4, 9, 2, 17, 3, 26]
['David Warner', 'KL\xa0Rahul', 'Quinton\xa0de Kock', 'Shikhar\xa0Dhawan', 'Andre\xa0Russell', 'Chris\xa0Gayle', 'Rishabh\xa0Pant', 'Virat\xa0Kohli', 'Shreyas\xa0Iyer', 'Jonny\xa0Bairstow', 'AB\xa0de Villiers', 'Suryakumar\xa0Yadav', 'MS\xa0Dhoni', 'Chris\xa0Lynn', 'Rohit\xa0Sharma', 'Hardik\xa0Pandya', 'Shane\xa0Watson', 'Faf\xa0du Plessis', 'Ajinkya\xa0Rahane', 'Suresh\xa0Raina', 'Parthiv\xa0Patel', 'Prithvi\xa0Shaw', 'Manish\xa0Pandey', 'Nitish\xa0Rana', 'Sanju\xa0Samson', 'Mayank\xa0Agarwal', 'Steve\xa0Smith', 'Jos\xa0Buttler', 'Shubman\xa0Gill', 'Ambati\xa0Rayudu', 'Robin\xa0Uthappa', 'Kieron\xa0Pollard', 'Dinesh\xa0Karthik', 'Vijay\xa0Shankar', 'Moeen\xa0Ali', 'David\xa0Miller', 'Marcus\xa0Stoinis', 'Colin\xa0Ingram', 'Krunal\xa0Pandya', 'Sarfaraz\xa0Khan', 'Nicholas\xa0Pooran', 'Mandeep\xa0Singh', 'Kedar\xa0Jadhav', 'Riyan\xa0Parag', 'Kane\xa0Williamson', 'Sunil\xa0Narine', 'Rahul\xa0Tripathi', 'Ben\xa0Stokes', 'Mohammad\xa0Nabi', 'Axar\xa0Patel', 'Ravindra\xa0Jadeja', 'Ishan\xa0Kishan', 'Yuvraj\xa0Singh', 'Gurkeerat\xa0Mann Singh', 'Sam\xa0Curran', 'Shimron\xa0Hetmyer', 'Wriddhiman\xa0Saha', 'Colin\xa0Munro', 'Martin\xa0Guptill', 'Dwayne\xa0Bravo', 'Sherfane\xa0Rutherford', 'Liam\xa0Livingstone', 'Stuart\xa0Binny', 'Jofra\xa0Archer', 'Deepak\xa0Hooda', 'Murali\xa0Vijay', 'Shreyas\xa0Gopal', 'Akshdeep\xa0Nath', 'Evin\xa0Lewis', 'Colin\xa0de Grandhomme', 'Piyush\xa0Chawla', 'Ravichandran\xa0Ashwin', 'Shivam\xa0Dube', 'Yusuf\xa0Pathan', 'Rinku\xa0Singh', 'Rashid\xa0Khan', 'Chris\xa0Morris', 'Mitchell\xa0Santner', 'Rahul\xa0Tewatia', 'Umesh\xa0Yadav', 'Amit\xa0Mishra', 'Harpreet\xa0Brar', 'Prayas\xa0Ray Barman', 'Keemo\xa0Paul', 'Ben\xa0Cutting', 'Krishnappa\xa0Gowtham', 'Simran\xa0Singh', 'Alzarri\xa0Joseph', 'Siddhesh\xa0Lad', 'Shardul\xa0Thakur', 'Kagiso\xa0Rabada', 'Bhuvneshwar\xa0Kumar', 'Kuldeep\xa0Yadav', 'Rahul\xa0Chahar', 'Mitchell\xa0McClenaghan', 'Carlos\xa0Brathwaite', 'Ishant\xa0Sharma', 'Shakib\xa0Al Hasan', 'Pawan\xa0Negi', 'Tim\xa0Southee']
['David Warner', 'KL Rahul', 'Quinton de Kock', 'Shikhar Dhawan', 'Andre Russell', 'Chris Gayle', 'Rishabh Pant', 'Virat Kohli', 'Shreyas Iyer', 'Jonny Bairstow', 'AB de Villiers', 'Suryakumar Yadav', 'MS Dhoni', 'Chris Lynn', 'Rohit Sharma', 'Hardik Pandya', 'Shane Watson', 'Faf du Plessis', 'Ajinkya Rahane', 'Suresh Raina', 'Parthiv Patel', 'Prithvi Shaw', 'Manish Pandey', 'Nitish Rana', 'Sanju Samson', 'Mayank Agarwal', 'Steve Smith', 'Jos Buttler', 'Shubman Gill', 'Ambati Rayudu', 'Robin Uthappa', 'Kieron Pollard', 'Dinesh Karthik', 'Vijay Shankar', 'Moeen Ali', 'David Miller', 'Marcus Stoinis', 'Colin Ingram', 'Krunal Pandya', 'Sarfaraz Khan', 'Nicholas Pooran', 'Mandeep Singh', 'Kedar Jadhav', 'Riyan Parag', 'Kane Williamson', 'Sunil Narine', 'Rahul Tripathi', 'Ben Stokes', 'Mohammad Nabi', 'Axar Patel', 'Ravindra Jadeja', 'Ishan Kishan', 'Yuvraj Singh', 'Gurkeerat Mann Singh', 'Sam Curran', 'Shimron Hetmyer', 'Wriddhiman Saha', 'Colin Munro', 'Martin Guptill', 'Dwayne Bravo', 'Sherfane Rutherford', 'Liam Livingstone', 'Stuart Binny', 'Jofra Archer', 'Deepak Hooda', 'Murali Vijay', 'Shreyas Gopal', 'Akshdeep Nath', 'Evin Lewis', 'Colin de Grandhomme', 'Piyush Chawla', 'Ravichandran Ashwin', 'Shivam Dube', 'Yusuf Pathan', 'Rinku Singh', 'Rashid Khan', 'Chris Morris', 'Mitchell Santner', 'Rahul Tewatia', 'Umesh Yadav', 'Amit Mishra', 'Harpreet Brar', 'Prayas Ray Barman', 'Keemo Paul', 'Ben Cutting', 'Krishnappa Gowtham', 'Simran Singh', 'Alzarri Joseph', 'Siddhesh Lad', 'Shardul Thakur', 'Kagiso Rabada', 'Bhuvneshwar Kumar', 'Kuldeep Yadav', 'Rahul Chahar', 'Mitchell McClenaghan', 'Carlos Brathwaite', 'Ishant Sharma', 'Shakib Al Hasan', 'Pawan Negi', 'Tim Southee']

In [720]:
df = pd.DataFrame(np.array([list(play), list(y_pred)]).T,
                  index=list(range(1,101)), columns=['PLAYER', '2020_Runs'])

df.to_excel(r'E:/flipr hackathon/problem_statement/result.xlsx', sheet_name='RESULT')